# Generated by Django 6.0 on 2025-12-16 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=10)),
                ('role', models.SmallIntegerField(choices=[(0, 'Employe'), (1, 'Responsable'), (2, 'Gerant')], default=0)),
                ('shop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='shop.shop')),
            ],
        ),
    ]
